name: Lint

on: 
  push:
    branches:
      - main

permissions: { }

jobs:
  build:
    name: Lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes
        id: changes
        run: echo ::set-output name=changed_files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

      - name: Super-linter
        uses: super-linter/super-linter@v6.4.1
        with:
          changed-files: ${{ steps.changes.outputs.changed_files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Format code with Prettier
        run: npx prettier --write .

      - name: Add changes made by Prettier
        run: git add .

      - name: Commit changes made by Prettier
        run: git commit -m "Apply Prettier formatting"

      - name: Push changes made by Prettier
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
