name: Super-Linter

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
    branches-ignore:
      - '*'

jobs:
  linter:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Node.js (required for ESLint and Prettier)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Install ESLint, Prettier, and Super-Linter
      - name: Setup
        uses: github/super-linter@v4
        with:
          linters: |
            - eslint
            - prettier

      # Run Prettier to format code
      - name: Format code with Prettier
        run: npx prettier --write .

      # Run ESLint to lint JavaScript files
      - name: Lint code with ESLint
        run: npx eslint .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
